spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/librarydb
    username: postgres
    password: postgres
#    driver-class-name: org.postgresql.Driver
